image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"
  OCAML: "ocaml-base-compiler.4.14.0"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/
  only:
  - master@iris/simuliris
  - /^ci/@iris/simuliris
  except:
  - triggers
  - schedules
  - api

## Build jobs

build-coq.8.15.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.15.1"
    DENY_WARNINGS: "1"

build-coq.8.14.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.14.1"
    MANGLE_NAMES: "1"
    DENY_WARNINGS: "1"

trigger-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.16.dev   coq-stdpp.dev git git+https://gitlab.mpi-sws.org/iris/stdpp.git#$STDPP_REV   coq-iris.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#$IRIS_REV"
  except:
  only:
  - triggers
  - schedules
  - api
